package com.quarkdown.core.ast.base.block

import com.quarkdown.core.ast.InlineContent
import com.quarkdown.core.ast.attributes.id.Identifiable
import com.quarkdown.core.ast.attributes.id.IdentifierProvider
import com.quarkdown.core.ast.attributes.localization.LocalizedKind
import com.quarkdown.core.ast.attributes.localization.LocalizedKindKeys
import com.quarkdown.core.ast.attributes.location.LocationTrackableNode
import com.quarkdown.core.ast.base.TextNode
import com.quarkdown.core.ast.base.block.Heading.Companion.marker
import com.quarkdown.core.ast.quarkdown.reference.CrossReferenceableNode
import com.quarkdown.core.visitor.node.NodeVisitor

/**
 * A heading defined via prefix symbols.
 * A heading is identifiable, as it can be looked up in the document and can be referenced.
 * It is also location trackable, meaning its position in the document hierarchy is determined, and possibly displayed.
 * @param depth importance (`depth=1` for H1, `depth=6` for H6)
 * @param customId optional custom ID. If `null`, the ID is automatically generated. If not `null`, the ID is used for cross-referencing.
 * @param canBreakPage whether this heading can trigger an automatic page break.
 *                     Decorative headings and auto-generated section headings typically disable this.
 * @param canTrackLocation whether this heading's position in the document hierarchy is tracked and displayed.
 *                         When `false`, the heading is not numbered and is not included in the table of contents.
 * @param excludeFromTableOfContents if `true`, this heading is never included in the table of contents,
 *                                   even if its location is trackable. Useful for headings generated by functions
 *                                   such as `.tableofcontents` and `.bibliography` to prevent self-referencing.
 */
class Heading(
    val depth: Int,
    override val text: InlineContent,
    val customId: String? = null,
    val canBreakPage: Boolean = true,
    override val canTrackLocation: Boolean = true,
    val excludeFromTableOfContents: Boolean = false,
) : TextNode,
    Identifiable,
    LocationTrackableNode,
    CrossReferenceableNode,
    LocalizedKind {
    override fun <T> accept(visitor: NodeVisitor<T>) = visitor.visit(this)

    override fun <T> accept(visitor: IdentifierProvider<T>) = visitor.visit(this)

    override val kindLocalizationKey: String
        get() = LocalizedKindKeys.HEADING

    /**
     * Whether this heading is decorative, i.e. it cannot trigger page breaks and its location is not tracked.
     */
    val isDecorative: Boolean
        get() = !canBreakPage && !canTrackLocation && excludeFromTableOfContents

    /**
     * If the heading has a custom ID, it can be used for cross-referencing.
     */
    override val referenceId: String?
        get() = this.customId

    /**
     * @return whether this heading is a marker
     * @see marker
     */
    val isMarker: Boolean
        get() = depth == MARKER_HEADING_DEPTH

    companion object {
        /**
         * When a [Heading] has this depth value, it is considered an invisible referenceable mark.
         * Depth 0 cannot be achieved with plain Markdown, but it can be supplied by a Quarkdown function.
         */
        private const val MARKER_HEADING_DEPTH = 0

        /**
         * Creates an invisible [Heading] that acts as a marker that can be referenced by other elements in the document.
         * A useful use case would be, for example, in combination with a [com.quarkdown.core.context.toc.TableOfContents].
         * Depth 0 cannot be achieved with plain Markdown, but it can be supplied by the Quarkdown function `.marker`.
         */
        fun marker(name: InlineContent) = Heading(MARKER_HEADING_DEPTH, name, canBreakPage = false)
    }
}
