# Paragraphs

I was born in the year 1632, in the city of York, of a good family, though not of that country, my father being a foreigner of Bremen, who settled first at Hull. He got a good estate by merchandise, and leaving off his trade, lived afterwards at York, from whence he had married my mother, whose relations were named Robinson, a very good family in that country, and from whom I was called Robinson Kreutznaer; but, by the usual corruption of words in England, we are now called—nay we call ourselves and write our name—Crusoe; and so my companions always called me.

I had two elder brothers, one of whom was lieutenant-colonel to an English regiment of foot in Flanders, formerly commanded by the famous Colonel Lockhart, and was killed at the battle near Dunkirk against the Spaniards. What became of my second brother I never knew, any more than my father or mother knew what became of me.

Being the third son of the family and not bred to any trade, my head began to be filled very early with rambling thoughts. My father, who was very ancient, had given me a competent share of learning, as far as house-education and a country free school generally go, and designed me for the law; but I would be satisfied with nothing but going to sea; and my inclination to this led me so strongly against the will, nay, the commands of my father, and against all the entreaties and persuasions of my mother and other friends, that there seemed to be something fatal in that propensity of nature, tending directly to the life of misery which was to befall me.

My father, a wise and grave man, gave me serious and excellent counsel against what he foresaw was my design. He called me one morning into his chamber, where he was confined by the gout, and expostulated very warmly with me upon this subject. He asked me what reasons, more than a mere wandering inclination, I had for leaving father’s house and my native country, where I might be well introduced, and had a prospect of raising my fortune by application and industry, with a life of ease and pleasure. He told me it was men of desperate fortunes on one hand, or of aspiring, superior fortunes on the other, who went abroad upon adventures, to rise by enterprise, and make themselves famous in undertakings of a nature out of the common road; that these things were all either too far above me or too far below me; that mine was the middle state, or what might be called the upper station of low life, which he had found, by long experience, was the best state in the world, the most suited to human happiness, not exposed to the miseries and hardships, the labour and sufferings of the mechanic part of mankind, and not embarrassed with the pride, luxury, ambition, and envy of the upper part of mankind. He told me I might judge of the happiness of this state by this one thing—viz. that this was the state of life which all other people envied; that kings have frequently lamented the miserable consequence of being born to great things, and wished they had been placed in the middle of the two extremes, between the mean and the great; that the wise man gave his testimony to this, as the standard of felicity, when he prayed to have neither poverty nor riches.

He bade me observe it, and I should always find that the calamities of life were shared among the upper and lower part of mankind, but that the middle station had the fewest disasters, and was not exposed to so many vicissitudes as the higher or lower part of mankind; nay, they were not subjected to so many distempers and uneasinesses, either of body or mind, as those were who, by vicious living, luxury, and extravagances on the one hand, or by hard labour, want of necessaries, and mean or insufficient diet on the other hand, bring distemper upon themselves by the natural consequences of their way of living; that the middle station of life was calculated for all kind of virtue and all kind of enjoyments; that peace and plenty were the handmaids of a middle fortune; that temperance, moderation, quietness, health, society, all agreeable diversions, and all desirable pleasures, were the blessings attending the middle station of life; that this way men went silently and smoothly through the world, and comfortably out of it, not embarrassed with the labours of the hands or of the head, not sold to a life of slavery for daily bread, nor harassed with perplexed circumstances, which rob the soul of peace and the body of rest, nor enraged with the passion of envy, or the secret burning lust of ambition for great things; but, in easy circumstances, sliding gently through the world, and sensibly tasting the sweets of living, without the bitter; feeling that they are happy, and learning by every day’s experience to know it more sensibly.

*From: Robinson Crusoe*