# Text formatting

## Emphasis

**You can't have light without dark.** You can't know *happiness* unless you've known **sorrow**. Let's have a ~~nice~~ *tree right here*. Now __we don't want him to get lonely__, so we'll give him a little _friend_.
We start with a ***vision*** in our **_heart_, and ~~we put it~~ on canvas**. If I *paint something*, **I don't want to *have* to explain** what it is.

## Code

After running **`quarkdown c file.qmd -p`**, a webserver will run on port `8089`.  
It may also be changed it via `--server-port <port>`.  
Combining `-p` with `-w` enables live content reload!

## Link

Did you know [Quarkdown's wiki](https://github.com/iamgio/quarkdown/wiki) is a great place to start? Check it out!

<<<

## Advanced formatting

.text {This} size:{large} decoration:{underoverline} is an .text {example} size:{larger} style:{italic} of .text {what you can do} decoration:{underline} with just a .text {few things} weight:{bold} decoration:{strikethrough}, a little imagination and a happy dream in your heart. .text {That easy} variant:{smallcaps}.

.text {The} size:{tiny} .text {quick} size:{small} .text {brown} size:{normal} .text {fox} size:{medium} .text {jumps} size:{larger} .text {over} size:{large} .text {the lazy dog} size:{huge}.

.text {The quick} decoration:{underline} .text {brown} decoration:{overline} .text {fox} decoration:{underoverline} .text {jumps over} decoration:{strikethrough} .text {the lazy dog} decoration:{all}.

.text {The quick} case:{lowercase} .text {brown fox} case:{uppercase} .text {jumps over the lazy dog} case:{capitalize}.

.text {The quick brown fox jumps over the lazy dog} variant:{smallcaps}.