package com.quarkdown.rendering.html.post

import com.quarkdown.core.context.Context
import com.quarkdown.core.media.storage.options.MediaStorageOptions
import com.quarkdown.core.media.storage.options.ReadOnlyMediaStorageOptions
import com.quarkdown.core.pipeline.output.ArtifactType
import com.quarkdown.core.pipeline.output.OutputResource
import com.quarkdown.core.pipeline.output.TextOutputArtifact
import com.quarkdown.core.rendering.PostRenderer
import com.quarkdown.rendering.html.node.SidebarRenderer
import com.quarkdown.rendering.html.post.document.HtmlDocumentBuilder

/**
 * A subset of [HtmlPostRenderer] that generates only the HTML output resources without any additional resources.
 *
 * It supports out of the box:
 * - RevealJS for slides rendering;
 * - PagedJS for page-based rendering (e.g. books);
 * - KaTeX for math rendering;
 * - HighlightJS for code highlighting.
 *
 * @param context the rendering context
 * @param name the name of the HTML output resource, without extension
 * @param relativePathToRoot the relative path to follow to get from the HTML resources generated by this post-renderer
 *                           to the root (the location where the main HTML file is located, alongside `script`, `theme`, etc.)
 */
class HtmlOnlyPostRenderer(
    private val context: Context,
    private val name: String = "index",
    private val relativePathToRoot: String,
) : PostRenderer {
    // HTML requires local media to be resolved from the file system.
    override val preferredMediaStorageOptions: MediaStorageOptions =
        ReadOnlyMediaStorageOptions(enableLocalMediaStorage = true)

    override fun wrap(content: CharSequence): CharSequence =
        HtmlDocumentBuilder(
            context,
            relativePathToRoot,
            sidebarContent = SidebarRenderer.render(context),
        ).build(content)

    /**
     * Generates a single HTML output resource with the given name and the rendered content, and no additional resources.
     */
    override fun generateResources(rendered: CharSequence): Set<OutputResource> =
        buildSet {
            this +=
                TextOutputArtifact(
                    name = name,
                    content = rendered,
                    type = ArtifactType.HTML,
                )
        }

    override fun wrapResources(
        name: String,
        resources: Set<OutputResource>,
    ) = resources.first()
}
