package com.quarkdown.core

/**
 * Targeted sources that exercise the lexers' edge cases, grouped by the token kind they cover.
 * The lexer snapshot test tokenizes every one of them.
 */
object LexerEdgeCases {
    /**
     * Sources exercising block-level recognizers.
     */
    val block: Map<String, List<String>> =
        linkedMapOf(
            "onelineMathSpacing" to
                listOf(
                    "$ Not math $ abc $ Not math $",
                    $$"$ Math $expression $",
                    "$ Math expression$ $",
                    "$ a  $ b $",
                    "$ Not math  $",
                    "$ Not math$",
                ),
            "midLineResume" to
                listOf("<!-- c -->rest", "<!-- c -->rest\nmore", "<!-- c --># H", "<<<   ", "<<<\t", "<!-- c --><!-- d -->", ".func {x}  "),
            "functionCall" to
                listOf(
                    ".func {x}",
                    ".func {x}\n    body",
                    ".func {x}\n    body\npara",
                    ".func {x}::chain {y}",
                    "{.func {x}}",
                    "{.func {x}",
                    ".func {x} trailing",
                    "text .func {x}",
                    "- .func {x}",
                    ".func {.inner {y}}",
                    ".func {x}\n    line1\n\n    line2",
                    "  .func {x}",
                ),
            "math" to
                listOf(
                    "$ x $",
                    "$ x $ {#i}",
                    $$"$ a$b $",
                    "$ x $ trailing",
                    $$"$x$",
                    "$$$\nx\n$$$",
                    "$$$ {#i}\nx\n$$$",
                    "$$$\nx",
                    "$$\nx\n$$",
                    "$$$\na\n\nb\n$$$",
                    "text $ x $ more",
                ),
            "pageBreak" to listOf("<<<", "<<<<", "<<<   ", "  <<<", "<<", "<<< x", "    <<<", "<<<\npara", "<<<\n\npara"),
            "comment" to
                listOf(
                    "<!-- c -->",
                    "<!-- c -->\npara",
                    "<!-- a\nb -->",
                    "<!-->",
                    "<!--->",
                    "<!-- unterminated",
                    "x <!-- c -->",
                    "<!-- c -->\n\npara",
                ),
            "table" to
                listOf(
                    "|a|b|\n|-|-|\n|1|2|",
                    "|a|b|\n|-|-|",
                    "|a|b|\n|:-:|-:|\n|1|2|",
                    "a|b\n-|-\n1|2",
                    "|a|b|\n|-|-|\n|1|2|\n\"cap\"",
                    "|a|b|\n|-|-|\n|1|2|\n\"cap\" {#id}",
                    "|a|b|\n|-|-|\n|1|2|\n\n|c|d|\n|-|-|",
                    "|a|b|\n|-|-|\n|1|2|\n# h",
                    "|a|b|\n|-|-|\n|1\\|x|2|",
                    "    |a|b|\n|-|-|",
                    "|a|b|\n|-|-| x\n|1|2|",
                ),
            "tableLarge" to listOf("|a|b|\n|-|-|\n" + List(5000) { "|$it|$it|" }.joinToString("\n")),
            "listItem" to
                listOf(
                    "- a",
                    "- a\n- b",
                    "- a\n  cont\n- b",
                    "- a\n\n  b\n- c",
                    "- a\nlazy",
                    "- \n- b",
                    "- [x] t",
                    "- [ ] t\n  c",
                    "- [ ] a\n\n  b\n- c",
                    "1. a\n2. b",
                    "  - a\n   - b\n     - [x] c",
                    "- a\n  - n1\n    - n2",
                    "- a\n  ```\n  code\n  ```",
                    "- a\n\n  para\n\n- b",
                ),
            "listItemLarge" to listOf(List(5000) { "- item $it" }.joinToString("\n")),
            "list" to
                listOf(
                    "- a\n- b",
                    "- a\n- b\n",
                    "- a\n* b",
                    "1. a\n2. b",
                    "1. a\n10. b",
                    "- a\nlazy",
                    "- a\n  cont",
                    "- a\n \n- b",
                    "- a\n  \n- b",
                    "- a\n\n\n- b",
                    "- ",
                    "-   a",
                    "- a\n  - b",
                    "- a\n\npara",
                    "- a\n# h",
                    "- a\n|h|h|\n|-|-|",
                    "    - a",
                ),
            "listLarge" to listOf(List(2000) { "- item $it" }.joinToString("\n")),
            "footnoteDefinition" to
                listOf(
                    "[^f]: one",
                    "[^f]: one\n",
                    "[^a]: x\n\n[^b]: y",
                    "[^f]: multi\nline\n\npara",
                    "[^f]:",
                    "[^f]: a\n# h",
                    "[^f]: a\n  more",
                    "[l]: u",
                    "[^]: x",
                    "    [^f]: x",
                ),
            "linkDefinition" to
                listOf(
                    "[l]: u",
                    "[l]: u\n",
                    "[l]: u\n\nP",
                    "[l]: <u>",
                    "[l]: u \"ti\"",
                    "[l]: u 'ti'",
                    "[l]: u (ti)",
                    "[l]:\n  u",
                    "[l]: u\n  \"ti\"",
                    "[l]: u rest",
                    "[l]: u \"ti\" rest",
                    "[l]: u\n\"ti\" rest",
                    "[l]:\tu",
                    "[\n\nl]: u",
                    "[a\nb]: u",
                    "[l]: /path)",
                    "[l]: /a(b)c",
                    "[l]: <a\\>b>",
                    "[l]: <a<b>",
                    "[l]: u 'a\n\nb'",
                    "[l]: foo\\ bar",
                    "[l]: u\t\"ti\"",
                    "[l]: u\n  'ti\nmore'",
                    "[l] u",
                    "[^l]: u",
                    "[]: u",
                    "    [l]: u",
                    "[a\\]b]: u",
                ),
            "setextHeading" to
                listOf(
                    "A\n===",
                    "A\n===\n",
                    "A\n---",
                    "A\nB\n===",
                    "A\n===\nB\n===",
                    "A {#i}\n===",
                    "- A\n===",
                    "===\n===",
                    "A\n===   ",
                    "A\n   ===",
                    "A\n    ===",
                    "A\n   \n===",
                    "A\n--",
                ),
            "fencedCode" to
                listOf(
                    "```\nc\n```",
                    "```\nc\n```\n",
                    "```lang\nc\n```",
                    "```lang \"cap\" {#i}\nc\n```",
                    "``` \"cap\"\nc\n```",
                    "``` {#i}\nc\n```",
                    "~~~\nc\n~~~",
                    "~~~\n```\n~~~",
                    "```\nc\n````",
                    "````\nc\n```\nd\n````",
                    "```\ncode ```\nstill code\n```",
                    "```\nc\n     ```",
                    "```\nc",
                    "```\nc\n~~~",
                    "```\na```",
                    "````\n```\n````",
                    "  ```\n  c\n  ```",
                    "```\nc",
                    "``\nc\n``",
                    "``` \"cap\nc\n```",
                ),
            "indentedCode" to
                listOf("    a", "    a\n", "    a\n\n    b", "    a\n\nb", "    a\n  \n  \nb", "     a", "    a\n     b", "   a", "    \n"),
            "indentedCodeTabs" to listOf("\tcode", "  \t code"),
            "blockQuote" to
                listOf(
                    "> q",
                    "> q\n",
                    "> a\n> b",
                    ">> d",
                    "> q\nlazy",
                    "> q\nlazy\n\n> q2",
                    "> \nlazy",
                    ">\nlazy",
                    "> q\n# h",
                    "> q\n\n> q2",
                    "   > q",
                    "    > q",
                    "> [!NOTE]\n> n",
                    "> a\n> - attr",
                ),
            "thematicBreak" to listOf("---", "---\n", "***\n\nP", "___", "   ---   ", "-\t-\t-", "--", "-*-", "--- a", "a\n---"),
            "heading" to
                listOf(
                    "# H",
                    "# H\n",
                    "# H\n\nP",
                    "# H\n   \nP",
                    "###### H",
                    "####### H",
                    "#",
                    "#!",
                    "#! D",
                    "### H ###",
                    "#### H####",
                    "# H #a#",
                    "# H {#i}",
                    "# H {#i} ##",
                    "   # H",
                    "    # H",
                    "#h",
                    "# H\n###\nP",
                ),
            "empty and blank" to listOf("", "\n", "\n\n", "   ", "   \n", "\t", " \n \n "),
            "paragraph" to
                listOf(
                    "a",
                    "a\n",
                    "a\nb",
                    "a\n\nb",
                    "a\n  b",
                    "a\n\tb",
                    "a\n   \nb",
                    "a\n# h",
                    "a\n#! h",
                    "a\n1. x",
                    "a\n10. x",
                    "a\n- x",
                    "a\n> q",
                    "a\n---",
                    "a\n```\nc\n```",
                    "a\n|h|h|\n|-|-|",
                    "a\n$$$\nx\n$$$",
                ),
        )

    /**
     * Sources exercising inline-level recognizers.
     */
    val inline: Map<String, List<String>> =
        linkedMapOf(
            "expression" to
                listOf(
                    ".f {x}",
                    ".f {x} more",
                    "  .f {x}",
                    "text .f {x}",
                    "\\.f {x}",
                    "{.f {x}}",
                    ".f {x}::g {y}",
                    ".f {x}\n    body",
                    "plain text",
                    "\\* .f {x}",
                ),
            "inlineFunctionCall" to
                listOf(
                    ".f {x}",
                    "text .f {x} more",
                    "a.f {x}",
                    "a..f {x}",
                    "\\.f {x}",
                    "{.f {x}}",
                    "{.f {x}",
                    ".f {x}::g {y}",
                    ".f {.g {y}}",
                    ".f {x} .g {y}",
                    "*.f {x}*",
                    ".f",
                ),
            "textSymbol" to
                listOf(
                    "(C)",
                    "(c)",
                    "(R)",
                    "(r)",
                    "(TM)",
                    "(tm)",
                    "a -- b",
                    "a--b",
                    "a - b",
                    "a-b",
                    "a...",
                    "...a",
                    "a...b",
                    "->",
                    "<-",
                    "=>",
                    "<==",
                    ">=",
                    "<=",
                    "!=",
                    "+-",
                    "don't",
                    "'a'",
                    "\"q\"",
                    "a \"q\" b",
                    "a 'q' b",
                ),
            "inlineMath" to
                listOf(
                    "$ x $",
                    "a $ x $ b",
                    "a$ x $",
                    $$"$ x $b",
                    $$"$x$",
                    $$"$ a$b $",
                    "$ a $ b $",
                    "$ x $ and $ y $",
                    "$ x",
                ),
            "image" to
                listOf(
                    "![i](u)",
                    "!(2x3)[i](u)",
                    "!(2*3)[i](u)",
                    "!(2 3)[i](u)",
                    "!(2)[i](u)",
                    "!(1cm*2cm)[i](u)",
                    "!(2X3)[i](u)",
                    "!(1cmx1cm)[i](u)",
                    "![i](u){#id}",
                    "![i]",
                    "![i][]",
                    "![i][r]",
                    "!(2x3)[i][r]",
                    "[![i](u)](u2)",
                    "!(x)[i](u)",
                ),
            "inlineComment" to
                listOf("a <!-- c --> b", "<!-- c -->", "<!-->", "<!--->", "<!-- unterminated", "a <!-- c"),
            "reference" to
                listOf(
                    "[l]",
                    "[l][]",
                    "[l][r]",
                    "[l][ ]",
                    "[^f]",
                    "[^f: d]",
                    "[^: d]",
                    "[^f:]",
                    "[^f: `code`]",
                    "[^f: a\\]b]",
                    "[a [b] c][r]",
                    "[f]",
                    "[l](u",
                ),
            "link" to
                listOf(
                    "[l](u)",
                    "[l](u \"t\")",
                    "[l](<u)",
                    "[l](a\\ b)",
                    "[l](u 't')",
                    "[l](u (t))",
                    "[l](<u v>)",
                    "[l]()",
                    "[l](a(b)c)",
                    "[l](a\\(b)",
                    "[a [b] c](u)",
                    "[a `b` c](u)",
                    "[a \\] b](u)",
                    "[l",
                    "[l](u",
                    "*[l](u)*",
                    "[*l*](u)",
                ),
            "autolink" to
                listOf(
                    "<http://x.com>",
                    "<a@b.com>",
                    "<mailto:>",
                    "http://x.com",
                    "HTTP://x.com",
                    "www.x.com",
                    "a@b.com",
                    "a@b-.com",
                    "http://x.com<y",
                    "http://xn--ls8h.la",
                    "http://\u00e9.com",
                ),
            "escape" to
                listOf(
                    "\\#",
                    "\\*",
                    "\\\\",
                    "\\_",
                    "\\`",
                    "\\[",
                    "\\a",
                    "\\",
                    "a\\-b",
                ),
            "entity" to
                listOf(
                    "&copy;",
                    "&copy",
                    "&#35;",
                    "&#x22;",
                    "&#X22;",
                    "&unknownname;",
                    "&",
                    "&#;",
                    "&#xZZ;",
                    "&colon;",
                ),
            "lineBreak" to
                listOf(
                    "a\nb",
                    "a  \nb",
                    "a   \nb",
                    "a\\\nb",
                    "a\n",
                    "a\n\n",
                    "a  \n\nb",
                    "a \nb",
                    "a\u2028b",
                ),
            "codeSpan" to
                listOf(
                    "`x`",
                    "``x``",
                    "` x `",
                    "``a`b``",
                    "`x",
                    "``",
                    "`x``",
                    "`a\nb`",
                    "`#FF0000`",
                    "a``b`",
                ),
            // Emphasis pairing follows the CommonMark algorithm, including the rule of three.
            "emphasis" to
                listOf(
                    "**text**",
                    "__text__",
                    "*text*",
                    "_text_",
                    "(__text)__",
                    "abc **strong abc** text **test** aaaa *emphasis*",
                    "abc __strong abc__ text __test__ aaaa _emphasis_",
                    "text **strong*x*m** text**strong**  ** not strong**",
                    "text __strong_x_m__ text__not strong__  __ not strong__",
                    "**strong *strongemphasis***",
                    "***strongemphasis***",
                    "foo***bar***baz",
                    "**foo__",
                    "*foo _bar* baz_",
                    "abc **def*g __h__ i*jkl** mno",
                    "~~del~~",
                    "~one~",
                    "~~~three~~~",
                    "*foo",
                    "a_b_c",
                    "**",
                    "***foo** bar*",
                    "*foo **bar** baz*",
                    "*foo **bar* baz**",
                    "*__foo__*",
                ),
            "empty and blank" to listOf("", "\n", " ", "  \n"),
        )
}
