package com.quarkdown.cli.creator.content

import com.quarkdown.cli.creator.template.ProjectCreatorTemplateProcessorFactory
import com.quarkdown.core.pipeline.output.OutputResource

/**
 * Supplier of the initial content of a new Quarkdown project.
 * This includes:
 * - The name of a precompiled JTE template whose rendering becomes the initial main-file content
 * - Additional resources (e.g. assets)
 * @see com.quarkdown.cli.creator.ProjectCreator
 */
interface ProjectCreatorInitialContentSupplier {
    /**
     * @return the name of the precompiled JTE template (e.g. `creator/initialcontent.qd.jte`)
     * whose rendered output is injected into the main file. The template is processed by the same
     * processor used by the [com.quarkdown.cli.creator.ProjectCreator], so all placeholder values
     * configured on the main template are available.
     * If `null`, no initial content is injected.
     * @see ProjectCreatorTemplateProcessorFactory
     */
    val templateName: String?

    /**
     * @return a collection of additional resources that are generated by this supplier.
     * This may include assets, additional files, etc.
     */
    fun createResources(): Set<OutputResource>
}
