package com.quarkdown.processor.generation

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.quarkdown.processor.model.FunctionDescriptor
import com.quarkdown.processor.model.ModuleDescriptor
import com.quarkdown.processor.model.ParameterDescriptor
import com.quarkdown.processor.util.backtick
import com.quarkdown.processor.util.backtickLastSegment

/**
 * Emits one Kotlin source per discovered [ModuleDescriptor]: an `object <ModuleName>`
 * containing synthetic wrappers around the source `@QFunction`s and a nested
 * `val Module: QuarkdownModule = moduleOf(::wrapper, ...)`.
 *
 * @param codeGenerator KSP [CodeGenerator] used to create the output streams
 */
class ModuleCodeGenerator(
    private val codeGenerator: CodeGenerator,
) {
    /**
     * Generates the source for [module] and writes it to KSP's output directory.
     */
    fun generate(module: ModuleDescriptor) {
        val dependencies = Dependencies(aggregating = false, module.file)
        val fileName = "${module.name}Module"

        codeGenerator
            .createNewFile(dependencies, module.packageName, fileName, extensionName = KOTLIN_EXTENSION)
            .bufferedWriter()
            .use { writer -> writer.write(render(module)) }
    }

    private fun render(module: ModuleDescriptor): String =
        buildString {
            appendLine("// Generated by quarkdown-native-library-processor. Do not edit.")
            // Ktlint scans KSP output when the plugin is applied to a KSP-enabled source set;
            // suppressing at the file level keeps generated code out of the linter's way.
            appendLine("@file:Suppress(")
            appendLine("    \"RedundantVisibilityModifier\",")
            appendLine("    \"RemoveRedundantBackticks\",")
            appendLine("    \"unused\",")
            appendLine("    \"ktlint:standard:annotation\",")
            appendLine("    \"ktlint:standard:argument-list-wrapping\",")
            appendLine("    \"ktlint:standard:chain-method-continuation\",")
            appendLine("    \"ktlint:standard:filename\",")
            appendLine("    \"ktlint:standard:function-naming\",")
            appendLine("    \"ktlint:standard:function-signature\",")
            appendLine("    \"ktlint:standard:import-ordering\",")
            appendLine("    \"ktlint:standard:max-line-length\",")
            appendLine("    \"ktlint:standard:no-unused-imports\",")
            appendLine("    \"ktlint:standard:parameter-list-wrapping\",")
            appendLine("    \"ktlint:standard:parameter-wrapping\",")
            appendLine("    \"ktlint:standard:paren-spacing\",")
            appendLine(")")
            appendLine()
            appendLine("package ${module.packageName}")
            appendLine()
            appendLine("import $QUARKDOWN_MODULE_FQN")
            appendLine("import $MODULE_OF_FQN")
            module.sourceImports?.let {
                appendLine()
                appendLine(it)
            }
            appendLine()
            appendLine("object ${module.name} {")
            appendModuleVal(module)
            module.functions.forEach { function ->
                appendLine()
                appendWrapper(function)
            }
            appendLine("}")
        }

    private fun StringBuilder.appendModuleVal(module: ModuleDescriptor) {
        appendLine("    val Module: QuarkdownModule =")
        appendLine("        moduleOf(")
        module.functions.forEach { function ->
            appendLine("            this::${function.exportedName.backtick()},")
        }
        appendLine("        )")
    }

    private fun StringBuilder.appendWrapper(function: FunctionDescriptor) {
        val parameters = function.parameters.joinToString(", ", transform = ::renderParameter)
        val returnType = KSTypeRenderer.render(function.returnType)
        val delegateArguments =
            function.parameters.joinToString(", ") {
                "${it.originalName.backtick()} = ${it.exportedName.backtick()}"
            }
        function.sourceAnnotations?.let { appendLine("    $it") }
        appendLine("    public fun ${function.exportedName.backtick()}($parameters): $returnType =")
        appendLine("        ${function.qualifiedName.backtickLastSegment()}($delegateArguments)")
    }

    private fun renderParameter(parameter: ParameterDescriptor): String {
        // Parameter annotations (@Injected, @Body, @LikelyNamed, ...) precede the declaration.
        val annotations = parameter.sourceAnnotations?.let { "$it " } ?: ""
        val signature = "$annotations${parameter.exportedName.backtick()}: ${KSTypeRenderer.render(parameter.type)}"
        return parameter.defaultExpression?.let { "$signature = $it" } ?: signature
    }

    private companion object {
        const val KOTLIN_EXTENSION = "kt"
        const val QUARKDOWN_MODULE_FQN = "com.quarkdown.core.function.library.module.QuarkdownModule"
        const val MODULE_OF_FQN = "com.quarkdown.core.function.library.module.moduleOf"
    }
}
