package com.quarkdown.core.flavor.quarkdown

import com.quarkdown.core.flavor.base.BaseMarkdownParserFactory

/**
 * [QuarkdownFlavor] parser factory.
 * Quarkdown parsing doesn't differ from the base one, as new nodes are generated by the lexer,
 * instead of the parser.
 */
typealias QuarkdownParserFactory = BaseMarkdownParserFactory
