import {DocumentHandler} from "../document-handler";

/**
 * Handler that swaps the width and height of elements with the `landscape` class.
 * This is useful for displaying landscape-oriented content in a portrait-oriented layout.
 *
 * Landscape elements are generated by Quarkdown's `.landscape` function.
 */
export class LandscapeSizeSwapper extends DocumentHandler {
    async onPreRendering() {
        const landscapeElements = document.querySelectorAll<HTMLElement>('.landscape');

        landscapeElements.forEach(element => {
            const width = element.clientWidth;
            const height = element.getBoundingClientRect().height;
            element.style.width = `${height}px`;
            element.style.height = `${width}px`;
        });
    }
}