package com.quarkdown.quarkdoc.reader.anchors

/**
 * Anchors are flag elements that can be used to mark specific sections of documentation.
 * Anchors are generated by Quarkdoc, and read by Quarkdoc-Reader to extract specific information.
 */
object Anchors {
    /**
     * Name of the anchor for optional parameters.
     */
    const val OPTIONAL = "optional"

    /**
     * Name of the anchor for likely named parameters.
     */
    const val LIKELY_NAMED = "likely-named"

    /**
     * Name of the anchor for likely body parameters.
     */
    const val LIKELY_BODY = "likely-body"

    /**
     * Name of the anchor for likely chained functions.
     */
    const val LIKELY_CHAINED = "likely-chained"

    /**
     * Name of the anchor for optionally present enum values of a parameter.
     */
    const val VALUES = "values"
}
