name: Update Emoji List
description: Generates emoji list using Quarkdown and commits it to the gh-pages-src branch
inputs:
  quarkdown-path:
    description: 'Path to the Quarkdown executable'
    required: true
    default: 'quarkdown'

runs:
  using: composite
  steps:
    - name: Generate emoji list
      run: ${{ inputs.quarkdown-path }} c .github/actions/update-emoji-list/generate.qd -o build/qd-ci --nowrap
      shell: bash

    - name: Setup gh-pages-src branch for emoji list commit
      run: |
        # Save the generated emoji list before switching branches
        cp build/qd-ci/emoji-list/index.html /tmp/emoji-list.html
        git stash || true
        git fetch origin gh-pages-src
        git checkout gh-pages-src
        # Copy built emoji list to layout/docs/emoji-list.html, suitable for inclusion in Hugo site,
        # prepending {{ define "main" }} and appending {{ end }} to the file.
        {
          echo '{{ define "main" }}'
          cat /tmp/emoji-list.html
          echo '{{ end }}'
        } > layouts/docs/emoji-list.html
      shell: bash

    - name: Commit emoji list to gh-pages-src branch
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "chore: update emoji list"
        commit_user_name: "github-actions"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        file_pattern: layouts/docs/emoji-list.html
