package eu.iamgio.quarkdown.cli.creator

import eu.iamgio.quarkdown.cli.creator.content.ProjectCreatorInitialContentSupplier
import eu.iamgio.quarkdown.pipeline.output.ArtifactType
import eu.iamgio.quarkdown.pipeline.output.OutputResource
import eu.iamgio.quarkdown.pipeline.output.TextOutputArtifact
import eu.iamgio.quarkdown.template.TemplateProcessor

/**
 *
 */
class ProjectCreator(
    private val templateProcessorFactory: ProjectCreatorTemplateProcessorFactory,
    private val initialContentSupplier: ProjectCreatorInitialContentSupplier,
    private val mainFileName: String,
) {
    /**
     * @return the template processor created by [templateProcessorFactory],
     * with also the initial content inside, supplied by [initialContentSupplier]
     */
    private fun createTemplateProcessor(): TemplateProcessor {
        val template: TemplateProcessor = templateProcessorFactory.create()

        // Initial content is processed via the same template processor.
        val initialContentCode =
            initialContentSupplier.templateCodeContent
                ?.let { template.copy(text = it).process() }

        // Processed initial content is injected into the main template.
        template.optionalValue(ProjectCreatorTemplatePlaceholders.INITIAL_CONTENT, initialContentCode)

        return template
    }

    /**
     * @return a collection of resources generated by this project creator
     */
    fun createResources(): Set<OutputResource> {
        val main =
            TextOutputArtifact(
                mainFileName,
                this.createTemplateProcessor().process().trim(),
                ArtifactType.QUARKDOWN,
            )

        return buildSet {
            add(main)
            addAll(initialContentSupplier.createResources())
        }
    }
}
