package com.quarkdown.rendering.html

import com.quarkdown.core.ast.attributes.id.IdentifierProvider
import com.quarkdown.core.ast.base.block.FootnoteDefinition
import com.quarkdown.core.ast.base.block.Heading
import com.quarkdown.core.context.Context
import com.quarkdown.core.rendering.NodeRenderer
import com.quarkdown.core.util.node.flattenedChildren
import com.quarkdown.core.util.node.toPlainText

/**
 * Provides identifiers for elements suitable for HTML rendering.
 * @param renderer renderer that this provider should use to convert nodes to plain text via [toPlainText]
 * @see IdentifierProvider
 */
class HtmlIdentifierProvider private constructor(
    private val renderer: NodeRenderer?,
    private val context: Context?,
) : IdentifierProvider<String> {
    private val uniqueAutoGeneratedHeadingIds: Map<Heading, String> by lazy {
        context
            ?.attributes
            ?.root
            ?.flattenedChildren()
            ?.filterIsInstance<Heading>()
            ?.let { headings ->
                val counts = mutableMapOf<String, Int>()

                headings.associateWith { heading ->
                    val baseId = heading.text.toPlainText(renderer).toURIString().let(::sanitizeId)
                    val customId = heading.customId

                    when {
                        customId != null ->
                            sanitizeId(customId).also { sanitizedCustomId ->
                                counts[sanitizedCustomId] = (counts[sanitizedCustomId] ?: 0) + 1
                            }
                        else -> {
                            val duplicateCount = counts[baseId] ?: 0
                            counts[baseId] = duplicateCount + 1
                            if (duplicateCount == 0) baseId else "$baseId-$duplicateCount"
                        }
                    }
                }
            } ?: emptyMap()
    }

    /**
     * Converts [this] string to a URI-like string removing special characters and replacing whitespaces with dashes.
     * Example: "Hello, World!" -> "hello-world"
     * @return URI-like string
     */
    private fun String.toURIString() =
        this
            .lowercase()
            .replace("\\s+".toRegex(), "-")
            .replace("[^\\p{L}\\p{N}-]".toRegex(), "")

    override fun visit(heading: Heading) =
        heading.customId
            ?.let(::sanitizeId)
            ?: uniqueAutoGeneratedHeadingIds[heading]
            ?: heading.text.toPlainText(renderer).toURIString().let(::sanitizeId)

    override fun visit(footnote: FootnoteDefinition): String =
        "__footnote-${footnote.label.toURIString()}"
            .let(::sanitizeId)

    companion object {
        /**
         * Creates an instance of [HtmlIdentifierProvider].
         * @param renderer renderer that this provider should use to convert nodes to plain text via [toPlainText]
         */
        fun of(
            renderer: NodeRenderer?,
            context: Context? = null,
        ) = HtmlIdentifierProvider(renderer, context)

        /**
         * Sanitizes a string for use as an HTML element `id` attribute:
         * - Strips characters that are problematic in CSS selectors and URL fragments
         *   (spaces, quotes, angle brackets, etc.).
         * - Ensures the result is not empty.
         * - Ensures the result does not start with a digit (#86).
         * @return a safe identifier string, possibly different from the original
         */
        fun sanitizeId(id: String): String {
            val stripped = id.replace("[\\s\"'<>&]".toRegex(), "")
            return when {
                stripped.isEmpty() -> "_"
                stripped.first().isDigit() -> "_$stripped"
                else -> stripped
            }
        }
    }
}
