package com.quarkdown.test

import com.quarkdown.core.function.error.FunctionCallRuntimeException
import com.quarkdown.rendering.markdown.extension.gfm
import com.quarkdown.test.util.DEFAULT_OPTIONS
import com.quarkdown.test.util.execute
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertIs

/**
 * Tests for headings, both Markdown-based and via the `.heading` primitive function.
 */
class HeadingTest {
    @Test
    fun `markdown heading`() {
        execute("# Title") {
            assertEquals("<h1>Title</h1>", it)
        }

        execute("## Ti*tl*e") {
            assertEquals("<h2>Ti<em>tl</em>e</h2>", it)
        }

        execute("#### .sum {3} {2}") {
            assertEquals("<h4>5</h4>", it)
        }

        execute("###### .text {Hello, **world**} size:{tiny}") {
            assertEquals(
                "<h6><span style=\"font-size: var(--qd-size-tiny, 1em);\">Hello, <strong>world</strong></span></h6>",
                it,
            )
        }
    }

    @Test
    fun `decorative heading`() {
        execute("#! Title") {
            assertEquals("<h1 data-decorative=\"\">Title</h1>", it)
        }
    }

    @Test
    fun `default id`() {
        execute(
            "## Title",
            options = DEFAULT_OPTIONS.copy(enableAutomaticIdentifiers = true),
        ) {
            assertEquals("<h2 id=\"title\">Title</h2>", it)
        }
    }

    @Test
    fun `custom id`() {
        execute("## Title {#custom-id}") {
            assertEquals("<h2 id=\"custom-id\">Title</h2>", it)
        }
    }

    @Test
    fun `custom id (gfm)`() {
        execute(
            "## Title {#custom-id}",
            renderer = { factory, ctx -> factory.gfm(ctx) },
        ) {
            assertEquals("<h2 id=\"custom-id\">Title</h2>\n\n", it)
        }
    }

    @Test
    fun `automatic id is not emitted (gfm)`() {
        execute(
            "## Getting Started",
            options = DEFAULT_OPTIONS.copy(enableAutomaticIdentifiers = true),
            renderer = { factory, ctx -> factory.gfm(ctx) },
        ) {
            assertEquals("## Getting Started\n\n", it)
        }
    }

    @Test
    fun `auto page break`() {
        execute(
            """
            .autopagebreak maxdepth:{4}
            ## A
            ### B
            ##### C
            """.trimIndent(),
        ) {
            assertEquals(
                "<h2 class=\"page-break\">A</h2>" +
                    "<h3 class=\"page-break\">B</h3>" +
                    "<h5>C</h5>",
                it,
            )
        }

        execute(
            """
            .doctype {paged}
            .noautopagebreak
            # A
            """.trimIndent(),
        ) {
            assertEquals("<h1>A</h1>", it)
        }
    }

    @Test
    fun `auto page break per document type`() {
        val markdownSource = "# A\n\n## B\n\n### C"
        val primitiveSource = ".heading {A} depth:{1}\n\n.heading {B} depth:{2}\n\n.heading {C} depth:{3}"

        listOf(markdownSource, primitiveSource).forEach { source ->
            listOf("plain", "docs").forEach { type ->
                execute(".doctype {$type}\n$source") {
                    assertEquals("<h1>A</h1><h2>B</h2><h3>C</h3>", it)
                }
            }

            // Depth=1
            execute(".doctype {paged}\n$source") {
                assertEquals("<h1 class=\"page-break\">A</h1><h2>B</h2><h3>C</h3>", it)
            }

            // Depth=2
            execute(".doctype {slides}\n$source") {
                assertEquals(
                    "<h1 class=\"page-break\">A</h1><h2 class=\"page-break\">B</h2><h3>C</h3>",
                    it,
                )
            }
        }

        // Headings generated by a table of contents.
        val tocSource = ".tableofcontents title:{TOC}\n\n# A"
        val tocNav =
            "<nav role=\"table-of-contents\" data-role=\"table-of-contents\"><ol>" +
                "<li data-target-id=\"a\" data-depth=\"1\"><a href=\"#a\">A</a></li>" +
                "</ol></nav>"

        execute(".doctype {plain}\n$tocSource", DEFAULT_OPTIONS.copy(enableAutomaticIdentifiers = true)) {
            assertEquals(
                "<h1 id=\"table-of-contents\">TOC</h1>$tocNav<h1 id=\"a\">A</h1>",
                it,
            )
        }

        execute(".doctype {paged}\n$tocSource", DEFAULT_OPTIONS.copy(enableAutomaticIdentifiers = true)) {
            assertEquals(
                "<h1 class=\"page-break\" id=\"table-of-contents\">TOC</h1>" +
                    tocNav +
                    "<h1 class=\"page-break\" id=\"a\">A</h1>",
                it,
            )
        }

        // Headings generated by a bibliography.
        val bibliographySource = ".bibliography {bib/bibliography.bib} title:{Bib}"

        fun assertStartsWith(
            prefix: String,
            output: CharSequence,
        ) = assertEquals(prefix, output.take(prefix.length).toString())

        execute(".doctype {plain}\n$bibliographySource") {
            assertStartsWith("<h1>Bib</h1>", it)
        }

        execute(".doctype {paged}\n$bibliographySource") {
            assertStartsWith("<h1 class=\"page-break\">Bib</h1>", it)
        }
    }

    @Test
    fun `heading primitive`() {
        execute(".heading {Hello} depth:{1}") {
            assertEquals("<h1>Hello</h1>", it)
        }

        execute(".heading {Hello} depth:{3}") {
            assertEquals("<h3>Hello</h3>", it)
        }
    }

    @Test
    fun `heading primitive with custom id`() {
        execute(".heading {Hello} depth:{2} ref:{my-id}") {
            assertEquals("<h2 id=\"my-id\">Hello</h2>", it)
        }
    }

    @Test
    fun `heading primitive unnumbered`() {
        execute(".heading {Hello} depth:{2} numbered:{no}") {
            assertEquals("<h2>Hello</h2>", it)
        }
    }

    @Test
    fun `heading primitive decorative`() {
        execute(".heading {Hello} depth:{2} numbered:{no} indexed:{no} breakpage:{no}") {
            assertEquals("<h2 data-decorative=\"\">Hello</h2>", it)
        }
    }

    @Test
    fun `heading primitive no page break`() {
        execute(".heading {Hello} depth:{1} breakpage:{no}") {
            assertEquals("<h1>Hello</h1>", it)
        }
    }

    @Test
    fun `heading primitive with styling`() {
        execute(".heading {Hello} depth:{2} foreground:{red} background:{blue} fontsize:{small}") {
            assertEquals(
                "<h2 style=\"color: rgba(255, 0, 0, 1.0); " +
                    "background-color: rgba(0, 0, 255, 1.0); " +
                    "font-size: var(--qd-size-small, 1em);\">Hello</h2>",
                it,
            )
        }
    }

    @Test
    fun `duplicate auto identifiers are disambiguated`() {
        execute(
            """
            ## Examples

            ## Examples

            ## Examples
            """.trimIndent(),
            options = DEFAULT_OPTIONS.copy(enableAutomaticIdentifiers = true),
        ) {
            assertEquals(
                "<h2 id=\"examples\">Examples</h2>" +
                    "<h2 id=\"examples-2\">Examples</h2>" +
                    "<h2 id=\"examples-3\">Examples</h2>",
                it,
            )
        }
    }

    @Test
    fun `duplicate custom identifiers are disambiguated`() {
        execute(
            """
            ## A {#shared}

            ## B {#shared}
            """.trimIndent(),
            options = DEFAULT_OPTIONS.copy(enableAutomaticIdentifiers = true),
        ) {
            assertEquals(
                "<h2 id=\"shared\">A</h2>" +
                    "<h2 id=\"shared-2\">B</h2>",
                it,
            )
        }
    }

    @Test
    fun `auto identifier collides with custom identifier`() {
        // A custom id is just another base id: it still participates in deduplication
        // when an auto-generated id from another heading would produce the same string.
        execute(
            """
            ## A {#examples}

            ## Examples
            """.trimIndent(),
            options = DEFAULT_OPTIONS.copy(enableAutomaticIdentifiers = true),
        ) {
            assertEquals(
                "<h2 id=\"examples\">A</h2>" +
                    "<h2 id=\"examples-2\">Examples</h2>",
                it,
            )
        }
    }

    @Test
    fun `custom identifiers that only collide after sanitization are disambiguated`() {
        // The deduplication key is the sanitized identifier, so customIds whose only difference
        // is stripped by sanitization (whitespace here) are recognised as a collision.
        execute(
            """
            ## A {#a b}

            ## B {#ab}
            """.trimIndent(),
            options = DEFAULT_OPTIONS.copy(enableAutomaticIdentifiers = true),
        ) {
            assertEquals(
                "<h2 id=\"ab\">A</h2>" +
                    "<h2 id=\"ab-2\">B</h2>",
                it,
            )
        }
    }

    @Test
    fun `digit-leading identifiers that collide after sanitization are disambiguated`() {
        execute(
            """
            ## A {#123}

            ## B {#_123}
            """.trimIndent(),
            options = DEFAULT_OPTIONS.copy(enableAutomaticIdentifiers = true),
        ) {
            assertEquals(
                "<h2 id=\"_123\">A</h2>" +
                    "<h2 id=\"_123-2\">B</h2>",
                it,
            )
        }
    }

    @Test
    fun `heading primitive with body argument`() {
        execute(
            """
            .heading depth:{3}
                Hello
            """.trimIndent(),
        ) {
            assertEquals("<h3>Hello</h3>", it)
        }
    }

    @Test
    fun `heading primitive depth out of range`() {
        assertFailsWith<FunctionCallRuntimeException> {
            execute(".heading {Hello} depth:{0}") {}
        }.also { exception ->
            assertIs<IllegalArgumentException>(exception.cause)
        }

        assertFailsWith<FunctionCallRuntimeException> {
            execute(".heading {Hello} depth:{7}") {}
        }.also { exception ->
            assertIs<IllegalArgumentException>(exception.cause)
        }
    }
}
