name: Deploy Wiki

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: iamgio/quarkdown/.github/actions/setup-environment@main

      - name: Build distribution
        uses: burrunan/gradle-cache-action@404534c34a2faa40430357a3183522a845b04f3b # v3.0.3
        with:
          job-id: main
          arguments: installDist

      - name: Deploy wiki
        uses: ./.github/actions/deploy-wiki
        with:
          quarkdown-path: ${{ github.workspace }}/build/install/quarkdown/bin/quarkdown
          github-token: ${{ secrets.COMMITTER_TOKEN }}
