name: PDF generation via Puppeteer

on:
  push:
    branches: [ "chrome-action" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Serve Files
      uses: Eun/http-server-action@v1
      with:
        directory: ${{ github.workspace }}
        port: 8080
        no-cache: false
        index-files: |
          ["$PWD/Quarkdown-Mock/index.html"]
        allowed-methods: |
          ["GET", "HEAD"]
        content-types: |
          {
            "appcache": "text/cache-manifest",
            "css": "text/css",
            "gif": "image/gif",
            "html": "text/html",
            "ico": "image/x-icon",
            "jpeg": "image/jpeg",
            "jpg": "image/jpeg",
            "js": "text/javascript",
            "json": "application/json",
            "png": "image/png",
            "txt": "text/plain",
            "xml": "text/xml"
          }
        log: "log.txt"

    - name: Wait for server to be ready
      run: |
        for i in {1..30}; do
          if curl --output /dev/null --silent --head --fail http://localhost:8080/Quarkdown-Mock/index.html; then
            echo "Server is up!"
            break
          fi
          echo "Waiting for server..."
          sleep 2
        done

    - uses: tj-actions/puppeteer@v5
      id: puppeteer
      with:
        files: |
          .github/workflows/generate-pdf.js

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mock-pdf
        path: output/mock.pdf
